Feature:  토로방 입장 퀴즈 API
bookmaru/MARU-SERVER pull request #21
Opened 2021-04-24 16:05 UTC by wjdrbs96

- 테스트 코드 작성 중 (다 짜고 말하겠삼 ㅎ)
- 퀴즈 실패하면 다시 방에 못들어오게 로직 짜야 할 듯
- advice 패키지 따로 팜

등등 같이 리뷰 했던 대로 // 추가적인건 다시 라이브로 봅시다 !

2021-04-26 12:12 UTC, KimDoubleB requested changes
수고 많으셨습니다 👍 
이 부분만 확인 부탁드려요 :)

2021-04-26 12:12 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/controller/GroupController.java
> +        System.out.println(userId);
print문은 제거하는게 좋을 것 같습니다 :)

2021-04-26 12:12 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/controller/TestController.java
> +            return "에러";
`"에러"`보다는
- 에러메시지 활용: `"Error: " + e.getMessage()`
- 상수 활용: `private static final ErrorMessage = "ERROR";`

등으로 변경해보는 것은 어떨까요?

2021-04-26 12:12 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/controller/UserController.java
> +            .add("test", tokenDto));
중요한 것은 아닙니다만, `Controller` 부분의 return 컨벤션이 다 맞지 않는 것 같습니다.
`ResponseEntity.ok()` 하고 줄바꿈 후에 `body`가 나온 곳도 있고,
이렇게 한번에 작성된 곳도 있고,
`.add` 할 때 인덱스가 들어가지 않은 곳도 있고...

제 생각엔 
```
return ResponseEntity.ok()
                .body(~~~~
                    .add(~~~~));
```

이런 식으로 진행하는 것이 괜찮지 않을까 싶네요 ^_^

2021-04-26 13:04 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/controller/GroupController.java
> +        System.out.println(userId);
앗 ! 엄청난 실수 ~~

2021-04-26 13:05 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/controller/TestController.java
> +            return "에러";
요것은 테스트라서 나중에 지울 것이라서 대충 적었습니다 !

2021-04-26 13:06 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/controller/UserController.java
> +            .add("test", tokenDto));
줄 바꿈 컨벤션은 바꾸면 좋을 거 같습니다 ~ ~ 
근데 add 의 키 값은 아직 정해지지 않아서 대충 test 라고 적었습니다 ㅎ ㅎ

2021-04-26 13:23 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/controller/TestController.java
> +            return "에러";
개발에 `대충`이 있군요?

2021-04-26 13:24 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/controller/UserController.java
> +            .add("test", tokenDto));
그럼 위처럼 일단 진행하시죠 ^_^

2021-04-26 14:39 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/controller/TestController.java
> +            return "에러";
ㅋ,ㅋ 요것은 토큰 발급 받을려고 임시로 만들어놔서 필요할 때 쓰십쇼

2021-04-27 13:54 UTC, KimDoubleB approved these changes
컨벤션은 다음 PR에 맞추시죠.

2021-04-27 13:54 UTC, merged