Refactor: 토론방 3개 이상 만들면 Error 반환 추가
bookmaru/MARU-SERVER pull request #33
Opened 2021-05-02 10:12 UTC by wjdrbs96

- 토론방 2개까지만 만들 수 있어서 3개 째 만들면 에러 반환하는 코드 수정했습니다.

이것저것 함 봐보시져 ~

2021-05-02 14:27 UTC, KimDoubleB requested changes

2021-05-02 14:27 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/service/GroupService.java
> +    // 테스트를 위해서 public
이게 테스트를 위해서 메서드가 Public 으로 오픈되는 건가요?

Private 메서드를 테스트 (또는 테스트 코드) 때문에 Public으로 바꾸는건 옳지 않다고 생각합니다 😂
- 테스트 때문에 객체지향이 깨지는 개념이라는 생각이 듭니다. 기존 목적은 Private인데, 테스트 때문에 Public으로 바꾼다하면 테스트의 역할을 다시 봐야하는 것이라는 생각이 듭니다. 

Private 메서드로 두고, 테스트 방향을 바꾸는 편이 좋을 것 같다는 생각이 듭니다.
- Private 메서드에 대해 독립적으로 수행될 수 있는 테스트 코드 작성으로 고민해보는 건 어떨까요? 너무 급하게 생각하지 말고, 조금 더 고민해보는 쪽으로요.
- 직접 불가능하다면 Mock 등을 통해 테스트 해볼 수 있지 않을까요?

+)
주석은 안다는 편이 좋을 것 같습니다. TODO 또는 저희가 추후 이해가 어려운 부분에서 추가하는 목적으로 쓰는 편이 좋아보입니다 😆

2021-05-02 15:17 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/GroupService.java
> +    // 테스트를 위해서 public
요것은 넥스트스텝을 할 때 테스트 코드를 위해서 메소드를  public 으로 열거나(실제 미션을 할 때도 이렇게 했던) or 박재성님께서 테스트 코드를 위한 생성자(실제 코드에서 사용되지 않더라도)를 만들어서 쓰는 것을 보았는데요. 그래서 나쁘진..? 않다고 생각하긴 했습니다.

- 테스트 코드를 위한 메소드를 새로 만드는 것은 좋지 않지만 생성자를 만드는 것은 뭐 나쁘지 않다고는 하더라구요 .. ㅎ..ㅎ

- private 메소드로 두고 테스트 방향을 바꾸는 것이 좋을 거 같다.
      -  Mock 으로 주입한다 했을 때 private 메소드 호출 못하는건 똑같을 거 같은데 좋은 방법 있으면 공유 해주시면 굿굿 !

그리고 이러한 고민도 해보았습니다.  

지금은 GroupService makeGroup  메소드 안에 하나의 트랜잭션으로 다 묶여있습니다. (토론방 만들수 있는지 여부의 검증 로직도 여기서 호출) 

그런데 이런게 아니라 GroupController에서 직접 검증 로직인 IsPossibleGroupMake 메소드를 호출 하는 식으로 하면 어떨 까 했습니다. (그러면 무조건 public 이 되니까..?) 기존꺼랑 지금 말한게 큰 차이는 없어 보이긴 해서 현재 로직으로 하긴 했는데 꼼꼼하게 보면 makeGroup 내의 트랜잭션에서 검증 로직을 뺄 수 있으니 좀 더 깔끔할 거 같기도 합니다 ! 

어떠신가요 ~? 테스트 코드에 대해서는 좀 더 많이 고민하고 공부해보아야 겠군요 😂

2021-05-02 15:37 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/service/GroupService.java
> +    // 테스트를 위해서 public
- 넵넵 ! 생성자 정도는 괜찮을 수는 있지만, private 메서드를 테스트를 위해 public으로 여는건 약간 기존 테스트라는 목적과 어긋난다고 생각합니당. 다시 말해서, **좋은 프로그램을 위해 테스트 코드를 짜는 것인데 캡슐화/객체지향을 깬다** 라는 느낌인거죠.
   - 이것에 대해 정답은 없는데, 저는 그냥 좋지 않다고 생각합니다. 이럴거면 다 public 해도 되는 것 아닌가? 라는 생각이 들어서요 ㅋㅋ 넥스트스탭의 경우엔 답을 알려주는 게 없던 것 같습니다? 같이 토론하는 방향으로 지나갔던...ㅋㅋㅋ
- Mock으로 주입해도 private 메서드는 호출 못하는 것이 맞죠ㅎㅎㅎ 그냥 Mock, Stub 등을 찾아보면서 다른 것들을 찾아보는게 좋지 않을까 했습니다. (저도 찾아봐야겠...죠?ㅋ)
- 후자에 말씀하신 부분이 좋은 것 같네요. 하나의 로직으로 다 뭉쳐놓는 것보다 쪼개서 하는 게 책임도 덜고 메서드 명도 확실히 정해두면 코드 읽기도 수월할 것 같습니다 👍

2021-05-02 16:04 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/GroupService.java
> +    // 테스트를 위해서 public
좋습니다 ~~ 한번 좀 더 고민해보면서 잘 설계해보겠습니다 ㅎ,ㅎ

2021-05-02 16:13 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/GroupService.java
> +    // 테스트를 위해서 public
[https://www.slipp.net/questions/253](https://www.slipp.net/questions/253) 좋은 글 인거 같군요~

2021-05-04 13:03 UTC, KimDoubleB approved these changes
수고하셨습니다 🙏🏻

2021-05-04 13:03 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/service/BookService.java
> +    }
Book 서비스에서 `GroupMakeDto`를 받아 책을 만든다는게 조금 이상하긴 하네요😂
- 중간에 책을 만드는데 필요한 정보만을 갖는 `BookSaveDto` 같은 클래스를 생성해서 따로 해주는 것이 좋을 것 같다는 생각
하지만 다음 번 model로 변경하면서 리팩터링 해보시죠.

2021-05-04 17:06 UTC, merged