Feature: diary(독서 일기장) 기능 추가
bookmaru/MARU-SERVER pull request #34
Opened 2021-05-02 17:03 UTC by KimDoubleB

- 독서 일기장 기능 추가
- 아래 API 기능 추가하였습니다.

| 메소드 | 경로                                        | 설명      |
| ------ | ------------------------------------------- | --------- |
| GET       | /diary        | 독서 일기장 목록 조회
| POST      | /diary        | 독서 일기장 작성(생성)
| GET       | /diary/{id}   | 독서 일기장 조회
| PUT       | /diary/{id}   | 독서 일기장 수정
| DELETE    | /diary/{id}   | 독서 일기장 삭제

- 파일이 많아 보기 어렵다면, 기능 단위로 커밋했으니 커밋 단위로 확인해주세요.
- 테스트 코드는 다른 PR로 올릴 예정입니다.

2021-05-03 00:04 UTC, wjdrbs96 requested changes

2021-05-03 00:04 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +    public List<DiaryListResponseDTO> getAllDiary(final Long userId) {
(Question) & (With Study)
- `getAllDiary` 
- `getOneDiary`

다이어리 전체 조회, 하나 조회 인 거 같은데 `@Transactional(read=only)` 와 같은 것이 아니라 그냥 `Transactional` 쓴 이유가 궁금합니다 ㅎ,ㅎ (이 어노테이션에 대해서는 같이 공부하면 좋을 듯 합니다.)

2021-05-03 00:04 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +                .collect(Collectors.toList());
(Good)

Stream 아주 잘 쓰는 군요 !

2021-05-03 10:57 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/controller/DiaryController.java
> +                        .add("diary", diaryService.getOneDiary(id, userId)));
앗 좋네용 수정할게용
=

2021-05-03 11:00 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/exception/common/NotExistException.java
> +public class NotExistException extends RuntimeException{
음... 일단 기존에 있던 것과 맞추기 위한 것도 있었고, Exception 클래스 중엔 unchecked exception는 RuntimeException 이 제일 상위 클래스로 알고 있어서 일단 이렇게 했습니다.

2021-05-03 11:02 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +    private void checkExistDiary(Long id) {
아직 테스트 코드를 짜진 않았지만, 저라면 어차피 저 메서드들이 '다른 메서드'에 포함되어 수행되는 것이므로 그 '다른 메서드'를 테스트하며 같이 검증할 수 있게 작성할 것 같네요 :)
- 근데 일단 짜봐야 알 것 같네요 ㅋㅋ😂

2021-05-03 11:02 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +    public List<DiaryListResponseDTO> getAllDiary(final Long userId) {
오우 `@Transactional` 학습 합시다아

2021-05-03 11:04 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/controller/DiaryController.java
> +                : ResponseEntity.ok().body(ResponseDto.fail("독서 일기장 작성 실패"));
`Mapper` 에서 Insert, Update의 경우 기본적(default)으로 변한 row의 값(개수)을 반환해주는 것으로 알고 있습니다.
결국엔 저게 다 실패하는 경우엔 DB에서 문제가 있어 insert, update를 실패한다고 보면 될 것 같네요. 혹시 틀린 부분 있으면 알려주시면 감사하겠습니다.

2021-05-03 11:54 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/controller/DiaryController.java
> +                : ResponseEntity.ok().body(ResponseDto.fail("독서 일기장 작성 실패"));
Fail은 400 에러를 반환하고 있는 거 같은데 실패하는 경우에는 `InternalServerException`로 잡거나 해서 500 에러를 반환하는게 더 적절한 것 같습니다.

2021-05-03 11:58 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +                .collect(Collectors.toList());
그리고 전체적으로 다 ResponseMessage 에서 작성한 것을 사용하기로 했으니 응답 메세지를 요걸로 수정하면 좋을 것 같습니다!

2021-05-03 12:09 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +    private void checkExistDiary(Long id) {
둘 다 괜찮은 방법이라 생각듭니다. (현재의 방법도 굿) 굳이 이런걸 고민해야 하나 싶기도 하면서도 한편으론 고민이 되기도 했던 주제인 거 같습니다.

- 검증 로직도 트랙잭션에 들어가야 하는가? 
- 테스트 코드는 어떤식으로 작성하는게 좋은가? 

에 대한 것이었고 말 그대로 (Discussion & Suggestion) 이라서 추후에 더 얘기해보시죵

2021-05-03 13:08 UTC, l2hyunwoo commented on src/main/java/kr/co/maru/demo/dto/diary/DiaryListResponseDTO.java
> +    public static DiaryListResponseDTO from(Diary diary) {
@wjdrbs96 이런걸 정적 팩토리 메서드라 하나요?

2021-05-03 13:20 UTC, l2hyunwoo reviewed
LGTM 👍🏻

2021-05-03 13:20 UTC, l2hyunwoo commented on src/main/java/kr/co/maru/demo/exception/common/NotExistException.java
> +public class NotExistException extends RuntimeException{
@KimDoubleB 이건 제 미천한 의견이지만 한 번 보면 좋을 것 같습니다.

https://cheese10yun.github.io/spring-guide-exception/

이곳에서도 보다시피 예외처리도 구조화를 시켜서 전체 BusinessLogic의 Exception을 wrapping 하는 느낌으로 exception을 설계하더라구요. NotExistException이 어떤 layer(라고 해야되나 계층이라고 해야되나)에 속하는 지 고려해보시면서 설계하면 좋을 것 같습니당

2021-05-03 13:20 UTC, l2hyunwoo commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +    }
- 제 코딩 습관이어서 그런가 저는 toEntity라고만 하면 "음.....? 어떤 entity"라는 생각부터 먼저 들 것 같아요. 물론 두 분이서 합의하신거면 괜찮은데 만약에 새로들어온 사람이 저 메서드를 처음 본다면? 저 DTO가 어떤 역할을 하는 지 한 눈에 파악하기 힘들 것 같아요.

- '1'이라는 숫자는 magic number인 것 같네요. Constant로 설정하시는 것은 어떻게 생각하시나요?

2021-05-03 13:33 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +    }
1이라는 숫자 보고 저는 바로 알 긴 했지만 그럼에도 매직넘버로 상수처리 하면 좀 더 보기 좋겠군요 GOOD !

2021-05-04 07:27 UTC, l2hyunwoo commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +        if (diaryMapper.checkByIdAndUserId(id, userId) == 0) {
error에 대한 넘버링은 대부분 0, -1로 잡는게 관습같은 거니까 보자마자 이해가 가능하면 그냥 놔둬도 될 것 같습니다만, 만약에 의미를 명확히 부여하고싶다면 상수처리하는게 좋겠죠?

2021-05-04 08:27 UTC, KimDoubleB commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +    }
- 상수화는 좋네요. 수정할게요.
- `toEntity` 같은 경우는 추후 JPA로 이전할 것을 대비해서 작성하였습니다. JPA에서는 Entity 객체가 활용되므로 네이밍은 그대로 갈 것 같네요. 또한 의미에 있어서는 현재 Diary~DTO에서 entity로 가고 있다는 것을 볼 수 있다시피, Diary의 Entity 객체로 가고 있다는 것을 알 수 있을 것 같네요 ☺️
- DTO 네이밍 및 역할에 대해 의문을 표하신 거라면, Diary 데이터를 저장하고 업데이트 하는 전송 용도의 Object를 의미하는 것이므로 네이밍에 충분히 표현되었다고 생각합니다. 😅

2021-05-04 08:49 UTC, wjdrbs96 commented on src/main/java/kr/co/maru/demo/service/DiaryService.java
> +        if (diaryMapper.checkByIdAndUserId(id, userId) == 0) {
좋은 리뷰 Very GOOD~~

2021-05-04 14:39 UTC, merged